/**
 * Global Teardown Hook
 * 
 * Runs once after all tests complete. Use this for global cleanup
 * such as stopping servers, cleaning up databases, or generating final reports.
 */

async function globalTeardown() {
  console.log('🧹 Starting global test teardown...');

  try {
    // Clean up test data
    await cleanupTestData();
    
    // Generate test reports
    await generateFinalReports();
    
    // Cleanup temporary files
    await cleanupTempFiles();
    
    // Stop application server if we started it
    await stopApplicationServer();
    
    console.log('✅ Global teardown completed successfully');
    
  } catch (error) {
    console.error('❌ Global teardown failed:', error);
    // Don't throw error in teardown to avoid masking test failures
  }
}

/**
 * Clean up test data created during test run
 */
async function cleanupTestData() {
  console.log('🗑️ Cleaning up test data...');
  
  try {
    // Clean up any global test data
    // This could involve API calls to delete test users, etc.
    console.log('✅ Test data cleanup completed');
  } catch (error) {
    console.error('⚠️ Test data cleanup failed:', error);
  }
}

/**
 * Generate final test reports and summaries
 */
async function generateFinalReports() {
  console.log('📊 Generating final reports...');
  
  try {
    const reportData = {
      timestamp: new Date().toISOString(),
      environment: process.env.NODE_ENV || 'test',
      browserVersions: await getBrowserVersions(),
      testSummary: 'Reports will be generated by Playwright reporters'
    };
    
    // Could save additional metadata or custom reports here
    console.log('📋 Report data collected:', JSON.stringify(reportData, null, 2));
    console.log('✅ Final reports prepared');
  } catch (error) {
    console.error('⚠️ Report generation failed:', error);
  }
}

/**
 * Get browser version information
 */
async function getBrowserVersions() {
  try {
    const { chromium, firefox, webkit } = require('@playwright/test');
    
    return {
      chromium: chromium.version(),
      firefox: firefox.version(),
      webkit: webkit.version()
    };
  } catch (error) {
    return { error: 'Could not retrieve browser versions' };
  }
}

/**
 * Clean up temporary files created during testing
 */
async function cleanupTempFiles() {
  console.log('📂 Cleaning up temporary files...');
  
  try {
    const fs = require('fs').promises;
    const path = require('path');
    
    // Clean up any temporary test files
    const tempDirs = ['temp', 'tmp', 'downloads'];
    
    for (const dir of tempDirs) {
      try {
        const dirPath = path.join(process.cwd(), dir);
        await fs.rmdir(dirPath, { recursive: true });
        console.log(`🗑️ Cleaned up ${dir} directory`);
      } catch (error) {
        // Directory might not exist, which is fine
      }
    }
    
    console.log('✅ Temporary files cleanup completed');
  } catch (error) {
    console.error('⚠️ Temporary files cleanup failed:', error);
  }
}

/**
 * Stop application server if we started it in global setup
 */
async function stopApplicationServer() {
  console.log('🛑 Checking if application server should be stopped...');
  
  try {
    // Only stop server if we started it ourselves
    // This would require tracking server state from global setup
    
    const shouldStopServer = process.env.PLAYWRIGHT_STOP_SERVER === 'true';
    
    if (shouldStopServer) {
      console.log('🔄 Stopping application server...');
      
      // Implementation would stop the server process
      // This could involve killing a process or calling an API endpoint
      
      console.log('✅ Application server stopped');
    } else {
      console.log('ℹ️ Leaving application server running');
    }
  } catch (error) {
    console.error('⚠️ Server shutdown failed:', error);
  }
}

export default globalTeardown;